language: java
jdk: oraclejdk8
sudo: false
before_install:
  - chmod +x mvnw
script: ./mvnw clean install
deploy:
  provider: heroku
  api_key:
    secure: 381dda18-1272-41fb-94bd-00671a434238
  app: greeting-service
  on:
    repo: rosh-sandbox/greeting-service